# main.yaml
trainer:
  num_epochs: 1000 
  num_steps: 10000 # early stop
  batch_size: 64
  learning_rate: 0.001
  output_dir: "/Users/zhangjiahao/Project/tic/results/train/${now:%Y-%m-%d_%H-%M-%S}"
  log_dir: "${trainer.output_dir}/logs"
  checkpoint_dir: "${trainer.output_dir}/checkpoints"
  resume_training: False   # Set to true to resume training from the last checkpoint
  start_epoch: 0  # The epoch from which to resume


model:
  num_layer: 3
  emb_dim: 512
  gnn_type: "gin"
  drop_ratio: 0.25

dataset:
  dataset_root: "/Users/zhangjiahao/Project/tic/data/example" # "/Users/zhangjiahao/Dataset/CODEX/upmc/dataset"
  region_ids: ["UPMC_c001_v001_r001_reg001", "UPMC_c001_v001_r001_reg004"]
  k: 3 # k-hop for microenvironment extraction
  microe_neighbor_cutoff: 200.0
  subset_cells: false
  center_cell_types: ['Tumor'] # ["Tumor","Tumor (CD15+)","Tumor (CD20+)","Tumor (CD21+)","Tumor (Ki67+)","Tumor (Podo+)"]