# main.yaml
hydra:
  run:
    dir: "./outputs/train/${now:%Y-%m-%d_%H-%M-%S}"  # Store logs with timestamp
    
trainer:
  num_epochs: 1000 
  num_steps: 10000 # early stop
  batch_size: 64
  learning_rate: 0.001
  output_dir: "{hydra.run.dir}"
  log_dir: "${trainer.output_dir}/logs"
  checkpoint_dir: "${trainer.output_dir}/checkpoints"
  resume_training: False   # Set to true to resume training from the last checkpoint
  start_epoch: 0  # The epoch from which to resume


model:
  num_layer: 3
  emb_dim: 512
  gnn_type: "gin" # ["gin","gcn","gat","graphsage"]
  drop_ratio: 0.25

dataset:
  dataset_root: "{absolute path}" # absolute path to your dataset(should have a sub folder named "Raw")
  region_ids: ["UPMC_c001_v001_r001_reg001", "UPMC_c001_v001_r001_reg004"] # set null to use all regions or a List of region id
  k: 3 # k-hop for microenvironment extraction
  microe_neighbor_cutoff: 200.0
  subset_cells: false
  center_cell_types: ['Tumor'] # ["Tumor","Tumor (CD15+)","Tumor (CD20+)","Tumor (CD21+)","Tumor (Ki67+)","Tumor (Podo+)"]