general:
  raw_dir: "/Users/zhangjiahao/Project/tic/data/example/voronoi" # directory containing raw data: {cell_data}.csv,{expression}.csv,{cell_features}.csv, {cell_types}.csv
  output_dir: "/Users/zhangjiahao/Project/tic/data/example/output" # output directory for pseudotime analysis
  data_root: "/Users/zhangjiahao/Project/tic/data/example" # root directory for your CellularGraphDataset to initialize, see space-gm tutorial for more details
  random_seed: 42 # random seed for reproducibility
  show_plots: True # whether to show plots or not

sampler:
  total_samples: 10000 # total number of samples to generate
  regions: 'all' # list of regions to sample from, 'all' for all regions . eg: ['region1', 'region2']
  cell_types: ['Tumor'] # list of cell types to sample from, 'all' for all cell types. eg: ['cell_type1', 'cell_type2']

embedding:
  methods: ['composition_vectors','expression_vectors'] # list of embedding methods to use, eg: ['composition_vectors','expression_vectors'], can use '+' to concatenate embeddings
  n_pca_components: 10
  cluster_method: 'kmeans' # clustering method to use, eg: 'kmeans', 'dbscan', 'hdbscan'
  n_clusters: 2 # number of clusters to use for clustering

pseudotime:
  start_nodes: [0, 1] # list of start nodes for pseudotime analysis, from 0 to n_clusters-1

causal:
  pseudotime_file: "/Users/zhangjiahao/Project/tic/data/example/output/embedding_analysis/expression_vectors/pseudotime/start_node_0/pseudotime.csv" # pseudotime file to use for causal inference
  method: 'GrangerCausality'         # Causal inference method to use ('GrangerCausality' or 'LinearRegressionWithControls')
  included_cell_types:                       # Cell types to include in the analysis
    - Tumor
    - Stromal
    - Immune
  included_biomarkers:                       # Biomarkers to include in the analysis
    - PanCK
    - aSMA
    - CD45
    - Vimentin
  sparsity_threshold: 0.1                    # Filter threshold for sparsity in biomarker data
  visualization:                             # Visualization settings
    top_results: 10                          # Number of top results to visualize by P-Value
    output_dir: ${general.output_dir}/visualization     # Output directory for visualizations  

#-------------------------------------------------------------------------------#
#-----Do Not Change Below This Line If you Dont Know What You Are Changing -----#
#-------------------------------------------------------------------------------#



dataset: # dataset configuration, pls follow space-gm tutorial for more details, here we use default values 
  raw_folder_name: "graph"
  processed_folder_name: "tg_graph"
  node_features:
    - "cell_type"
    - "SIZE"
    - "biomarker_expression"
    - "neighborhood_composition"
    - "center_coord"
  edge_features:
    - "edge_type"
    - "distance"
  cell_type_mapping: ${constants.CELL_TYPE_MAPPING_UPMC}
  cell_type_freq: ${constants.CELL_TYPE_FREQ_UPMC}
  biomarkers: ${constants.BIOMARKERS_UPMC}
  subgraph_size: 3
  subgraph_source: "chunk_save"
  subgraph_allow_distant_edge: true
  subgraph_radius_limit: 200
  biomarker_expression_process_method: "linear"
  biomarker_expression_lower_bound: 0
  biomarker_expression_upper_bound: 18
  neighborhood_size: 10


constants:
  BIOMARKERS_UPMC:
    - CD11b
    - CD14
    - CD15
    - CD163
    - CD20
    - CD21
    - CD31
    - CD34
    - CD3e
    - CD4
    - CD45
    - CD45RA
    - CD45RO
    - CD68
    - CD8
    - CollagenIV
    - HLA-DR
    - Ki67
    - PanCK
    - Podoplanin
    - Vimentin
    - aSMA

  CELL_TYPE_MAPPING_UPMC:
    APC: 0
    B cell: 1
    CD4 T cell: 2
    CD8 T cell: 3
    Granulocyte: 4
    Lymph vessel: 5
    Macrophage: 6
    Naive immune cell: 7
    Stromal / Fibroblast: 8
    Tumor: 9
    Tumor (CD15+): 10
    Tumor (CD20+): 11
    Tumor (CD21+): 12
    Tumor (Ki67+): 13
    Tumor (Podo+): 14
    Vessel: 15
    Unassigned: 16

  CELL_TYPE_FREQ_UPMC:
    APC: 0.038
    B cell: 0.066
    CD4 T cell: 0.095
    CD8 T cell: 0.078
    Granulocyte: 0.027
    Lymph vessel: 0.006
    Macrophage: 0.103
    Naive immune cell: 0.034
    Stromal / Fibroblast: 0.077
    Tumor: 0.109
    Tumor (CD15+): 0.061
    Tumor (CD20+): 0.021
    Tumor (CD21+): 0.054
    Tumor (Ki67+): 0.134
    Tumor (Podo+): 0.063
    Vessel: 0.034
    Unassigned: 0.001
